### ISSUE TITLE
Optimize reachability

### ISSUE THREAD

**Issue by cejanen** [strvcom/ios-networking#36]
https://www.avanderlee.com/swift/optimizing-network-reachability/

**Comment by matejmolnar** [comment]
@cejanen what should be the purpose of this task? What I understood from the article is to simply adjust `URLSessionConfiguration` parameters according to your use case. You can then pass this configuration to our APIManager and that's it, or am I missing something? 🤔

**Comment by matejmolnar** [comment]
I see, thank you 🙏
