### ISSUE TITLE
Authentication vs. Authorization

### ISSUE THREAD

**Issue by brenovaladao** [strvcom/ios-networking#37]
I believe we have the wrong terminology in the library, we have it as Authorization, but in fact, it needs to be Authentication:
- Authentication regards a use sign-in into our system
- Authorization regards the access level a user has in a system (admin, user, etc)

**Comment by gajddo00** [comment]
I believe the terminology is right. 
- Authentication - the process of a user proving they are who they really are
- Authorisation - the process of determining whether a certain user has access to a resource

and as we are using OAuth based solution, there is no authentication involved, hence the 'Authorisation' header.

**Comment by cejanen** [comment]
@brenovaladao what do you think about @gajddo00 answer? Can you suggest some changes you would like to do? It's possible we're not 100% right with naming at all places but from begging we tried to follow other libraries & standards
